# Generated by Django 5.0.4 on 2024-04-26 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('idusers', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenom', models.CharField(default='', max_length=50)),
                ('role', models.CharField(choices=[('MEDECIN', 'Médecin'), ('PATIENT', 'Patient')], default='', max_length=10)),
                ('email', models.CharField(default='', max_length=50, unique=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='medecin',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialite', models.CharField(default='', max_length=50)),
                ('mobile', models.IntegerField(default='')),
                ('date_de_naissance', models.DateField(default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.users',),
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('poids', models.FloatField(default=0.0)),
                ('taille', models.FloatField(default=0.0)),
                ('mobile', models.IntegerField(default=0)),
                ('allergies', models.CharField(default='', max_length=50)),
                ('groupe_sanguin', models.CharField(default='', max_length=5)),
                ('date_de_naissance', models.DateField(default='')),
                ('type_diabete', models.CharField(default='', max_length=10)),
                ('sexe', models.CharField(default='', max_length=10)),
                ('idmed', models.ForeignKey(db_column='idmed_id', on_delete=django.db.models.deletion.CASCADE, to='api.medecin')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.users',),
        ),
        migrations.CreateModel(
            name='consultations',
            fields=[
                ('idconsultations', models.AutoField(primary_key=True, serialize=False)),
                ('date_consultation', models.DateField(default='')),
                ('heure_consultation', models.TimeField(default=None)),
                ('ordonnance', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('bilan', models.TextField(default='')),
                ('idmede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medecin')),
                ('idpat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
