# Generated by Django 5.0.4 on 2024-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_consultations_bilan_pdf_doctorchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
