# Generated by Django 5.0.4 on 2024-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='archived',
            field=models.BooleanField(default=True),
        ),
    ]
