# Generated by Django 5.0.4 on 2024-05-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='archived',
        ),
    ]
